endpoints:
  # WORKING EXAMPLES
  - url: https://www.google.com
    type: http
    method: GET
    expected_status: 200
  
  - url: https://api.github.com
    type: http
    method: GET
    expected_status: 200
    headers:
      Accept: application/vnd.github.v3+json
  
  - type: dns
    host: google.com
    record_type: A
  
  - type: dns
    host: one.one.one.one
    record_type: A
    expected: 1.1.1.1
  
  - type: tcp
    host: 8.8.8.8
    port: 53
  
  # FAILING EXAMPLES
  - url: https://this-domain-definitely-does-not-exist-12345.com
    type: http
    method: GET
    expected_status: 200
  
  - url: https://httpstat.us/404
    type: http
    method: GET
    expected_status: 200
  
  - type: dns
    host: nonexistent-host-that-will-fail-12345.com
    record_type: A
  
  - type: dns
    host: google.com
    record_type: A
    expected: 192.0.2.1
  
  - type: tcp
    host: google.com
    port: 9999
